**This is the second section of learning. The first section is on supervised learning and later develops Univariate Linear Regression through a general model, then deriving a cost function, and finally introduction to gradient descent**

**Here we work on Multiple Linear Regression and more sophisticated methods of regression analysis**

In [1]:
import random as rand
import numpy as np
import matplotlib.pyplot as plt

# Multiple Linear Regression General Model
x_s = np.array([1, 1, 0, 1])
w_s = np.array([5, 2, 5, 6])
b = 8

# Both x(inputs) and weights are vectors and can be operated on using vector methods

f_wb = np.dot(w_s,x_s) + b
print(f_wb)

21


**Vectorization is how we can take advantage of GPU/Parrallelism in out Devices to compute large updates and computation in shorter amount of times.**

Multiple Linear Regression Full Implementation with vectorization

In [2]:
import random as rand
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Dataset initialization and printing
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

df = pd.DataFrame(X_train, columns=['Size', '# of Bedrooms', '# of Floors', 'Age'])
df2 = pd.DataFrame(y_train, columns=['Price'])

print(df)
print(df2)

   Size  # of Bedrooms  # of Floors  Age
0  2104              5            1   45
1  1416              3            2   40
2   852              2            1   35
   Price
0    460
1    232
2    178


In [ ]:
# Initialize Weights and Bias values

w = np.zeros(4)
b = rand.randint(0,50)

print("Initialized values for Weights Vector(w) and Bias(b)")
print(f"w = {w}")
print(f"b = {b}")

Initialized values for Weights Vector(w) and Bias(b)
w = [0. 0. 0. 0.]
b = 49


In [ ]:
# Define Model Function

def f_wb(x, w, b):
    return np.dot(x,w) + b

print(f_wb(w, X_train[0], b))

49.0


In [ ]:
# Define a Cost Function

def J(x, y, w, b):
    error = f_wb(x, w, b) - y
    return (1/(2*len(x)))*sum(error**2)

print("Initial Cost From Weights and Bias")
print(X_train, y_train, w, b)
print(J(X_train, y_train, w, b))

Initial Cost From Weights and Bias
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]] [460 232 178] [0. 0. 0. 0.] 49
36508.5


In [ ]:
# Define Derivative and Gradient Descent Algorithm

def der_J_w(x, y, w, b):
    delta = 0.0001
    grads = np.zeros(len(w))
    for i in range(len(w)):
        w_plus = w.copy()
        w_plus[i] += delta
        grads[i] = (J(x,y, w_plus,b) - J(x, y, w, b))/delta
    print(grads)
    return grads

def der_J_b(x, y, w, b):
    delta = 0.0001
    der = (J(x,y, w,b+delta) - J(x,y, w,b))/delta
    print(der)
    return der

def grad_desc(x, y, w, b):
    alpha = 1e-7
    tmp_w = w - alpha*der_J_w(x, y, w, b)
    tmp_b = b - alpha*der_J_b(x, y, w, b)
    w = tmp_w
    b = tmp_b
    return w, b

w, b = grad_desc(X_train, y_train, w, b)
print(w, b)


[ 7.65208189e+03  1.41195755e+01  6.33088970e+00 -8.91015318e+01]
-5.504830819518247
[ 0.34041632 -6.65781688 -7.65781496 -4.65780175] 5.995469139390823


In [ ]:
# Training Stage

epoch = 25
w = np.zeros(4)
b = rand.randint(0,50)

for i in range(len(w)):
    w[i] = rand.randint(0,10)

for i in range(epoch):
    w, b = grad_desc(X_train, y_train, w, b)
    print(f"Epoch {i} | Loss = {J(X_train, y_train, w, b)} | w = {w} | b = {b}")

[2.35883513e+07 5.42740002e+04 1.91140002e+04 5.97410081e+05]
14423.999935388565
Epoch 0 | Loss = 67572862.87528577 | w = [7.64116487 3.9945726  3.9980886  1.94025899] | b = 41.998557600006464
[1.79567041e+07 4.13140774e+04 1.45598055e+04 4.54886124e+05]
10983.979403972626
Epoch 1 | Loss = 39159468.558389895 | w = [5.84549447 3.99044119 3.99663262 1.89477038] | b = 41.99745920206607
[1.36695948e+07 3.14482946e+04 1.10929102e+04 3.46389312e+05]
8365.252539515495
Epoch 2 | Loss = 22693764.802097876 | w = [4.47853498 3.98729636 3.99552333 1.86013145] | b = 41.996622676812116
[1.04060195e+07 2.39379366e+04 8.45372539e+03 2.63795771e+05]
6371.738575398922
Epoch 3 | Loss = 13151814.403264828 | w = [3.43793304 3.98490257 3.99467796 1.83375187] | b = 41.995985502954575
[7.92161241e+06 1.82206530e+04 6.44463757e+03 2.00921177e+05]
4854.169748723507
Epoch 4 | Loss = 7622216.025686523 | w = [2.64577179 3.9830805  3.99403349 1.81365975] | b = 41.9955000859797
[6.03034972e+06 1.38683527e+04 4.91521

**Optimization Techniques: Feature Scaling, Learning Rate, Feature Engineering**

**Feature Scaling Methods**
- Max Feature Scaling: Divides all values in a feature by the max value, restricts to [0, 1]
- Mean Feature Scaling: Computes mean and performs: (x - mu)/(max-min) to get values centered around [-1,1]
- Z scale normalization: calculated standard deviation and mean and normalizes by: x = (x - mu)/sigma

In [24]:
# Max Feature Scaling

df = pd.DataFrame(X_train, columns=['Size', '# of Bedrooms', '# of Floors', 'Age'])
df2 = pd.DataFrame(y_train, columns=['Price'])

print("Unscaled values")
print(df)
print(df2)

print("Max Feature Scaling")
features_set = []
for i in range(len(X_train[0])):
    tmp = []
    for j in range(len(X_train)):
        tmp.append(X_train[j][i])
    features_set.append(tmp)

features_set = np.array(features_set)

max = np.zeros(len(features_set))
for i in range(len(features_set)):
    max[i] = features_set[i].max()
X_train_max = X_train.copy()
X_train_max = np.array(X_train_max, dtype='float')
for i in range(len(X_train_max[0])):
    for j in range(len(X_train_max)):
        X_train_max[j][i] = X_train_max[j][i] / max[i]

df = pd.DataFrame(X_train_max, columns=['Size', '# of Bedrooms', '# of Floors', 'Age'])
print(df)

# Mean Normalize
print("Mean Normalize")
mean = np.zeros(len(features_set))
for i in range(len(features_set)):
    mean[i] = features_set[i].mean()

min = np.zeros(len(features_set))
for i in range(len(features_set)):
    min[i] = features_set[i].min()

X_train_mean = X_train.copy()
X_train_mean = np.array(X_train_mean, dtype='float')
for i in range(len(X_train_mean[0])):
    for j in range(len(X_train_max)):
        X_train_mean[j][i] = (X_train_mean[j][i] - mean[i])/(max[i] - min[i])

df = pd.DataFrame(X_train_mean, columns=['Size', '# of Bedrooms', '# of Floors', 'Age'])
print(df)

Unscaled values
   Size  # of Bedrooms  # of Floors  Age
0  2104              5            1   45
1  1416              3            2   40
2   852              2            1   35
   Price
0    460
1    232
2    178
Max Feature Scaling
       Size  # of Bedrooms  # of Floors       Age
0  1.000000            1.0          0.5  1.000000
1  0.673004            0.6          1.0  0.888889
2  0.404943            0.4          0.5  0.777778
Mean Normalize
       Size  # of Bedrooms  # of Floors  Age
0  0.516507       0.555556    -0.333333  0.5
1 -0.033014      -0.111111     0.666667  0.0
2 -0.483493      -0.444444    -0.333333 -0.5


Different Learning rates can lead to different convergences. You don't want it too small since that will take too long, but too big and it will overshoot.
- Try these values: [0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1]

In [ ]:
# We are not restricted to linear functions for regression.
# We can use any degree to get different curves
# here we implement x squared
def f_poly_wb(x, w, b):
    return w[0]*x[0] + w[1]*((x[1])**2) + b